import { interpretStep } from './interpreter.js';
import path from 'path';
import fs from 'fs';

/**
 * Export a parsed .flow file as a Playwright .spec.ts file.
 * The generated file is valid TypeScript that runs with:
 *   npx playwright test login.spec.ts
 */
export function exportToPlaywright(flow, outputDir = '.plaintest') {
  fs.mkdirSync(outputDir, { recursive: true });

  const lines = [];
  const baseName = path.basename(flow.filePath, '.flow');
  const outPath  = path.join(outputDir, `${baseName}.spec.ts`);

  // Header
  lines.push(`import { test, expect } from '@playwright/test';`);
  lines.push(``);
  lines.push(`/**`);
  lines.push(` * Generated by plaintest from: ${flow.filePath}`);
  lines.push(` * Do not edit manually — re-run plaintest --export to regenerate.`);
  lines.push(` * https://github.com/promptqa/plaintest`);
  lines.push(` */`);
  lines.push(``);

  // Test config block if non-defaults
  const hasConfig = flow.browser !== 'chromium' || !flow.headless || flow.viewport?.width !== 1280;
  if (hasConfig) {
    lines.push(`test.use({`);
    if (flow.browser !== 'chromium') {
      lines.push(`  // browser: set in playwright.config.ts — use --project=${flow.browser}`);
    }
    if (flow.viewport) {
      lines.push(`  viewport: { width: ${flow.viewport.width}, height: ${flow.viewport.height} },`);
    }
    lines.push(`});`);
    lines.push(``);
  }

  // Tags as annotation
  const tagAnnotation = flow.tags?.length
    ? `  tag: [${flow.tags.map(t => `'@${t}'`).join(', ')}],\n  `
    : `  `;

  lines.push(`test('${escTs(flow.name)}', async ({ page }) => {`);
  lines.push(``);

  // Navigate to base URL if set
  if (flow.url) {
    const firstRaw = flow.steps[0]?.raw?.toLowerCase() || '';
    if (!firstRaw.match(/^(?:navigate|go to|open)/)) {
      lines.push(`  // Base URL from .flow file`);
      lines.push(`  await page.goto('${flow.url}');`);
      lines.push(``);
    }
  }

  // Steps
  for (const step of flow.steps) {
    const s   = interpretStep(step.raw);
    const ts  = stepToTs(s, step.raw, flow);
    lines.push(`  // ${step.raw}`);
    if (ts) {
      lines.push(`  ${ts}`);
    } else {
      lines.push(`  // TODO: step not yet supported in export — run plaintest to execute`);
    }
    lines.push(``);
  }

  lines.push(`});`);
  lines.push(``);

  const content = lines.join('\n');
  fs.writeFileSync(outPath, content, 'utf8');
  return outPath;
}

function stepToTs(s, raw, flow) {
  const timeout = flow.timeout !== 30000 ? `, { timeout: ${flow.timeout} }` : ``;

  switch (s.action) {

    // NAVIGATION
    case 'navigate':
      return `await page.goto('${s.url}'${timeout ? `, { waitUntil: 'domcontentloaded', timeout: ${flow.timeout} }` : ``});`;
    case 'reload':
      return `await page.reload();`;
    case 'back':
      return `await page.goBack();`;
    case 'forward':
      return `await page.goForward();`;

    // CLICK
    case 'click':
      return `await ${resolveLocatorTs('page', s.target)}.click();`;
    case 'dblclick':
      return `await ${resolveLocatorTs('page', s.target)}.dblclick();`;

    // FILL
    case 'fill':
      return `await page.getByLabel(/${escReg(s.field)}/i).fill('${escTs(s.value)}');`;
    case 'clear':
      return `await page.getByLabel(/${escReg(s.field)}/i).clear();`;

    // SELECT
    case 'select':
      return `await page.getByRole('combobox', { name: /${escReg(s.field)}/i }).selectOption({ label: '${escTs(s.option)}' });`;

    // CHECK
    case 'check':
      return `await page.getByLabel(/${escReg(s.label)}/i).check();`;
    case 'uncheck':
      return `await page.getByLabel(/${escReg(s.label)}/i).uncheck();`;

    // KEYBOARD
    case 'press':
      return `await page.keyboard.press('${escTs(s.key)}');`;

    // HOVER
    case 'hover':
      return `await ${resolveLocatorTs('page', s.target)}.hover();`;

    // SCROLL
    case 'scroll':
      return `await ${resolveLocatorTs('page', s.target)}.scrollIntoViewIfNeeded();`;

    // ASSERTIONS
    case 'assertHeading':
      return `await expect(page.getByRole('heading', { name: /${escReg(s.text)}/i })).toBeVisible()${timeout ? `.toBeVisible({ timeout: ${flow.timeout} })` : ''};`;
    case 'assertVisible':
      return `await expect(page.getByText(/${escReg(s.text)}/i)).toBeVisible()${timeout};`;
    case 'assertHidden':
      return `await expect(page.getByText(/${escReg(s.text)}/i)).toBeHidden()${timeout};`;
    case 'assertUrlContains':
      return `await expect(page).toHaveURL(/${escReg(s.text)}/)${timeout};`;
    case 'assertUrl':
      return `await expect(page).toHaveURL('${escTs(s.url)}')${timeout};`;
    case 'assertTitle':
      return `await expect(page).toHaveTitle(/${escReg(s.text)}/i)${timeout};`;
    case 'assertValue':
      return `await expect(page.getByLabel(/${escReg(s.field)}/i)).toHaveValue('${escTs(s.value)}')${timeout};`;
    case 'assertDisabled':
      return `await expect(${resolveLocatorTs('page', s.target)}).toBeDisabled()${timeout};`;
    case 'assertEnabled':
      return `await expect(${resolveLocatorTs('page', s.target)}).toBeEnabled()${timeout};`;
    case 'assertPageContains':
      return `await expect(page.getByText(/${escReg(s.text)}/i).first()).toBeVisible()${timeout};`;
    case 'assertExists':
      return `await expect(page.locator('${s.selector}')).toBeVisible()${timeout};`;
    case 'assertNotExists':
      return `await expect(page.locator('${s.selector}')).toBeHidden()${timeout};`;

    // WAITS
    case 'wait':
      return `await page.waitForTimeout(${s.ms});`;
    case 'waitForVisible':
      return `await page.getByText(/${escReg(s.text)}/i).waitFor({ state: 'visible'${timeout ? `, timeout: ${flow.timeout}` : ''} });`;
    case 'waitForHidden':
      return `await page.getByText(/${escReg(s.text)}/i).waitFor({ state: 'hidden'${timeout ? `, timeout: ${flow.timeout}` : ''} });`;
    case 'waitForNetwork':
      return `await page.waitForLoadState('networkidle');`;

    // UTILITIES
    case 'screenshot':
      if (s.name) return `await page.screenshot({ path: '${s.name}.png', fullPage: true });`;
      return `await page.screenshot({ path: \`screenshot-\${Date.now()}.png\`, fullPage: true });`;
    case 'log':
      return `console.log('${escTs(s.message)}');`;

    case 'unknown':
      return null;

    default:
      return null;
  }
}

function resolveLocatorTs(page, target) {
  // CSS/XPath selectors used directly
  if (target.startsWith('#') || target.startsWith('.') || target.startsWith('//') || target.startsWith('[')) {
    return `${page}.locator('${escTs(target)}')`;
  }
  // Default: try button first, fall back to generic text
  return `${page}.getByRole('button', { name: /${escReg(target)}/i }).or(${page}.getByRole('link', { name: /${escReg(target)}/i })).or(${page}.getByText(/${escReg(target)}/i)).first()`;
}

function escTs(s) {
  return String(s || '').replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

function escReg(s) {
  return String(s || '').replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
